
spring.application.name=jpaPratica
spring.datasource.url=postgresql://practica_g2ca_user:qoHGiLlU7GYNdydJJHxTr1KK6RxdiemH@dpg-d45786s9c44c7382svv0-a/practica_g2ca
spring.datasource.username=practica_g2ca_user
spring.datasource.password=qoHGiLlU7GYNdydJJHxTr1KK6RxdiemH
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuración del email


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hidalg0antonio2002@gmail.com
spring.mail.password=izjytisiwuqxgxez
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
